// frontend/src/components/Button.jsx
export function Button({ children, onClick, className, selected = false }) {
  return (
    <div
      onClick={onClick}
      className={`${className} font-semibold group-hover:group-hover:block text-center hover:bg-pink-400 duration-100 ${selected ? 'bg-pink-400' : 'bg-neutral-700'} px-2.5 py-1.5 rounded cursor-pointer mr-2`}>
      {children}
    </div>
  )
}

// cmd/server/solid-frontend/src/components/Button.tsx
import { Component, JSX } from "solid-js"

type Props = {
  children: JSX.Element
  onClick: VoidFunction
  class?: string
  selected?: boolean
}

const Button: Component<Props> = (props) => {
  return (
    <div
      onClick={props.onClick}
      class={`${props.class} font-semibold group-hover:group-hover:block text-center hover:bg-blue-400 duration-100 ${props.selected ? 'bg-blue-400' : 'bg-neutral-700'} px-2.5 py-1.5 rounded cursor-pointer mr-2`}>
      {props.children}
    </div>
  )
}

export default Button
