// frontend/src/components/Paginator.jsx
import { Button } from "./Button";

export default function Paginator({ pageNumber, currentPage, onClick, onChange }) {
  return (
    <div className='flex flex-row justify-center items-center mb-6'>
      {
        new Array(pageNumber).fill().map((_, index) => (
          <Button
            selected={currentPage === index + 1}
            key={index}
            onClick={() => {
              onClick(index + 1)
              onChange()
            }}
          >
            {index + 1}
          </Button>
        ))
      }
    </div>
  )
}

// cmd/server/solid-frontend/src/components/Paginator.tsx
import { Component, For } from "solid-js";
import Button from "./Button";

type Props = {
  pageNumber: number
  currentPage: number
  onClick: Function
  onChange: Function
}

const Paginator: Component<Props> = ({ pageNumber, currentPage, onClick, onChange }) => {
  return (
    <div class='flex flex-row justify-center items-center mb-6'>
      <For each={new Array(pageNumber).fill(0)}>{(_, index) =>
        <Button
          selected={currentPage === index() + 1}
          onClick={() => {
            onClick(index() + 1)
            onChange()
          }}
        >
          {index() + 1}
        </Button>
      }</For>
    </div>
  )
}

export default Paginator
