// cmd/server/frontend/src/Gallery.jsx
import clsx from "clsx"
import { Fragment, useEffect, useRef, useState } from "react"
import { CgArrowLeft, CgArrowRight, CgBackspace, CgExpand, CgSandClock, CgViewSplit } from 'react-icons/cg'
import { useNavigate } from 'react-router-dom'
import MediaPlayer from './components/MediaPlayer'
import QuickAction from './components/QuickAction'
import Spinner from './components/Spinner'
import { getHost, getHostStatic } from "./utils"

export default function Gallery() {
  const [galleryTitle] = useState([window.location.pathname.split("/").slice(-1)] ?? "-")
  const [currentIndex, setCurrentIndex] = useState(0)
  const [showCounter, setShowCounter] = useState(false)
  const [galleryData, setGalleryData] = useState([])
  const [autoEnabled, setAutoEnabled] = useState(false)
  const [fullscreen, setFullScreen] = useState(false)
  const [splitView, setSplitView] = useState(false)
  const [loading, setLoading] = useState(true)

  const navigate = useNavigate()
  const slideshowTimer = useRef()

  const imgLoaded = () => {
    setLoading(false)
    showCounterTimeout()
  }

  const videoLoaded = () => {
    setLoading(false)
    showCounterTimeout()
  }

  const reset = () => {
    setLoading(true)
  }

  const showCounterTimeout = () => {
    setShowCounter(true)
    setTimeout(() => setShowCounter(false), 1000)
  }

  const startSlideShow = async () => {
    await document.getElementById('galleryMain').requestFullscreen()
    setAutoEnabled(state => !state)
    setTimeout(handleNext, 1000)
    slideshowTimer.current = setInterval(handleNext, 5000)
  }

  const stopSlideShow = async () => {
    await document.exitFullscreen()
    if (slideshowTimer.current) {
      clearInterval(slideshowTimer.current)
    }
    setAutoEnabled(state => !state)
  }

  useEffect(() => {
    (async () => {
      const res = await fetch(`${getHost()}/overlay/gallery?dir=${galleryTitle}`)
      if (res.redirected || res.status != 200) {
        navigate('/login')
      }
      const data = await res.json()

      if (data.avifAvailable) {
        setGalleryData(data.avif)
        return
      }
      if (data.webpAvailable) {
        setGalleryData(data.webp)
        return
      }
      setGalleryData(data.source)
      return
    })();
  }, [galleryTitle])

  useEffect(() => {
    const handler = (event) => {
      switch (event.key) {
        case 'ArrowLeft':
          handlePrev()
          window.scrollTo({ top: 0, left: 0, behavior: "auto" })
          break
        case 'ArrowRight':
          handleNext()
          window.scrollTo({ top: 0, left: 0, behavior: "auto" })
          break
        case 'v':
          setSplitView(state => !state)
          break
        case 's':
          setFullScreen(state => !state)
          break
        case 'p':
          autoEnabled ? stopSlideShow() : startSlideShow()
          break
        case 'Backspace':
          navigate('/')
          break
        default: break
      }
    }
    document.onkeydown = handler
  }, [currentIndex, galleryData])

  const handleNext = () => {
    if (splitView) {
      setCurrentIndex(state => (state + 2) % galleryData.length)
    } else {
      setCurrentIndex(state => (state + 1) % galleryData.length)
    }
    reset()
  }
  const handlePrev = () => {
    if (splitView) {
      setCurrentIndex(state => (state - 2) % galleryData.length)
    } else {
      setCurrentIndex(state => (state - 1) < 0 ? (galleryData.length - 1) : (state - 1))
    }
    reset()
  }

  const handleMobileTap = (event) => {
    event.clientX > window.innerWidth / 2 ? handleNext() : handlePrev()
  }

  return (
    <main id="galleryMain">
      <nav className="fixed w-14 h-full bg-transparent hover:bg-neutral-800 flex flex-col items-center justify-between px-8 duration-100 opacity-90 text-center group">
        <div className="flex flex-col items-center mt-8">
          <QuickAction
            onClick={() => navigate("/")}
            description="Back"
            className="hidden group-hover:group-hover:block"
          >
            <CgBackspace />
          </QuickAction>
          <QuickAction
            onClick={() => setSplitView(state => !state)}
            description="Split"
            className="hidden group-hover:group-hover:block"
          >
            <CgViewSplit />
          </QuickAction>
          <QuickAction
            onClick={() => setFullScreen(state => !state)}
            description="Span-H"
            className="hidden group-hover:group-hover:block"
          >
            <CgExpand />
          </QuickAction>
          <QuickAction
            selected={autoEnabled}
            onClick={() => autoEnabled ? stopSlideShow() : startSlideShow()}
            description="Auto"
            className="hidden group-hover:group-hover:block"
          >
            <CgSandClock />
          </QuickAction>
        </div>
        <div>
          <QuickAction
            onClick={handleNext}
            className="hidden group-hover:group-hover:block"
          >
            <CgArrowLeft />
          </QuickAction>
          <QuickAction
            onClick={handlePrev}
            className="hidden group-hover:group-hover:block"
          >
            <CgArrowRight />
          </QuickAction>
        </div>
        <div></div>
        <div></div>
        <div className="hidden group-hover:group-hover:block text-sm mb-3">
          Fuu v1.2
        </div>
      </nav>
      <aside className="fixed mt-8 mr-8 right-0 w-28 h-14 rounded-lg bg-transparent hover:bg-neutral-800 flex flex-col items-center justify-center px-2 duration-100 opacity-90 text-center group">
        <div className="hidden group-hover:group-hover:block w-full">
          <select
            value={currentIndex}
            className='rounded px-2.5 py-1.5 bg-neutral-800'
            onChange={(e) => setCurrentIndex(e.target.value)}>
            {
              galleryData.map((_, idx) => (
                <option value={idx} key={idx}>{idx + 1}</option>
              ))
            }
          </select>
        </div>
      </aside>
      <footer className={clsx(
        showCounter ? 'bg-neutral-800' : 'bg-transparent',
        'fixed bottom-8 left-1/2 -translate-x-1/2 w-40 h-40 rounded-lg flex flex-col items-center justify-center px-3 duration-150 opacity-90 text-center group'
      )}>
        <div className="flex justify-center">
          <div className={clsx(
            showCounter ? 'block' : 'hidden',
            'font-semibold text-5xl text-blue-400'
          )}>
            {Number(currentIndex) + 1} / {galleryData.length}
          </div>
        </div>
      </footer>
      <div className="flex justify-center items-center">
        {galleryData && galleryData.length > 0 &&
          !splitView ?
          <MediaPlayer
            onClick={handleMobileTap}
            onImageLoad={imgLoaded}
            onVideoLoad={videoLoaded}
            fullscreen={fullscreen}
            loading={loading}
            src={`${getHostStatic()}/${galleryTitle}/${galleryData.at(currentIndex)}`}
          /> :
          <Fragment>
            <MediaPlayer
              onClick={handleMobileTap}
              onImageLoad={imgLoaded}
              onVideoLoad={videoLoaded}
              fullscreen={fullscreen}
              loading={loading}
              src={`${getHostStatic()}/${galleryTitle}/${galleryData.at(currentIndex + 1)}`}
            />
            <MediaPlayer
              onClick={handleMobileTap}
              onImageLoad={imgLoaded}
              onVideoLoad={videoLoaded}
              onEnded={handleNext}
              fullscreen={fullscreen}
              loading={loading}
              src={`${getHostStatic()}/${galleryTitle}/${galleryData.at(currentIndex)}`}
            />
          </Fragment>
        }
      </div>
      {loading &&
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
          <Spinner />
        </div>
      }
    </main>
  )
}

// cmd/server/solid-frontend/src/Gallery.tsx
import { useLocation, useNavigate, useRouteData } from "@solidjs/router"
import clsx from "clsx"
import { CgArrowLeft, CgArrowRight, CgBackspace, CgExpand, CgSandClock, CgViewSplit } from "solid-icons/cg"
import { Component, createEffect, createResource, createSignal, Show } from "solid-js"
import MediaPlayer from "./components/MediaPlayer"
import QuickAction from "./components/QuickAction"
import Spinner from "./components/Spinner"
import { getHostOverlay, getHostStatic } from "./utils/url"

async function fetcher(path: string) {
  const res = await fetch(`${getHostOverlay()}/gallery?dir=${path}`)
  if (!res.ok) {
    window.location.href = '/login'
    throw new Error(`Error: ${res.status}`)
  }
  const data: GalleryResponse = await res.json()

  if (data.avifAvailable) {
    return data.avif
  }
  if (data.webpAvailable) {
    return data.webp
  }
  return data.source
}

const Gallery: Component = () => {
  let main: HTMLDivElement

  let slideshowTimer: number

  const [_, path] = useLocation().pathname.split('/gallery/')
  const [data] = createResource(path, fetcher)

  const navigate = useNavigate()
  const [index, setIndex] = createSignal(0)

  const [mediaLoading, setMediaLoading] = createSignal(true)
  const [autoEnabled, setAutoEnabled] = createSignal(false)
  const [showCounter, setShowCounter] = createSignal(false)
  const [fullscreen, setFullscreen] = createSignal(false)
  const [splitView, setSplitView] = createSignal(false)

  const handleNext = () => {
    setShowCounter(true)
    setMediaLoading(true)
    setIndex((index() + 1) % data().length)
  }

  const handlePrev = () => {
    setShowCounter(true)
    setMediaLoading(true)
    setIndex((index() <= 0 ? data().length - 1 : index() - 1) % data().length)
  }

  createEffect(() => {
    if (showCounter()) {
      setTimeout(() => setShowCounter(false), 750)
    }
  })

  createEffect(async () => {
    if (autoEnabled()) {
      await main.requestFullscreen()
      slideshowTimer = setInterval(() => handleNext(), 5000)
      return
    }
    if (document.fullscreenElement) {
      await document.exitFullscreen()
    }
    clearInterval(slideshowTimer)
  })

  createEffect(() => {
    document.onkeyup = (e: KeyboardEvent) => {
      switch (e.key) {
        case 'ArrowLeft':
          handlePrev()
          break
        case 'ArrowRight':
          handleNext()
          break
        case 'Backspace':
          navigate('/')
          break
        case 'v':
          setSplitView(state => !state)
          break
        case 's':
          setFullscreen(state => !state)
          break
        case 'p':
          setAutoEnabled(false)
          break
        default:
          break
      }
    }
  })

  return (
    <div class="bg-neutral-900 min-h-screen" ref={main}>
      <nav class="fixed w-14 h-full bg-transparent hover:bg-neutral-800 flex flex-col items-center justify-between px-8 duration-100 opacity-90 text-center group">
        <div class="flex flex-col items-center mt-8">
          <QuickAction
            onClick={() => navigate("/")}
            description="Back"
            class="hidden group-hover:group-hover:block"
          >
            <CgBackspace />
          </QuickAction>
          <QuickAction
            onClick={() => setSplitView(state => !state)}
            description="Split"
            class="hidden group-hover:group-hover:block"
          >
            <CgViewSplit />
          </QuickAction>
          <QuickAction
            onClick={() => setFullscreen(state => !state)}
            description="Span-H"
            class="hidden group-hover:group-hover:block"
          >
            <CgExpand />
          </QuickAction>
          <QuickAction
            selected={autoEnabled()}
            onClick={() => setAutoEnabled(state => !state)}
            description="Auto"
            class="hidden group-hover:group-hover:block"
          >
            <CgSandClock />
          </QuickAction>
        </div>
        <div>
          <QuickAction
            onClick={handleNext}
            class="hidden group-hover:group-hover:block"
          >
            <CgArrowLeft />
          </QuickAction>
          <QuickAction
            onClick={handlePrev}
            class="hidden group-hover:group-hover:block"
          >
            <CgArrowRight />
          </QuickAction>
        </div>
        <div></div>
        <div></div>
        <div class="hidden group-hover:group-hover:block text-sm mb-3">
          Fuu v2.0-solid
        </div>
      </nav>
      <Show when={!data.loading} fallback={<Spinner />}>
        <div class="flex items-center justify-center">
          <Show when={mediaLoading()}>
            <div class="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 z-50">
              <Spinner />
            </div>
          </Show>
          <Show when={!splitView()}>
            <MediaPlayer
              onLoad={() => setMediaLoading(false)}
              loading={mediaLoading()}
              fullscreen={fullscreen()}
              src={`${getHostStatic()}/${path}/${data().at(index())}`}
            />
          </Show>
          <Show when={splitView()}>
            <MediaPlayer
              onLoad={() => setMediaLoading(false)}
              loading={mediaLoading()}
              fullscreen={fullscreen()}
              src={`${getHostStatic()}/${path}/${data().at(index())}`}
            />
            <MediaPlayer
              loading={mediaLoading()}
              onLoad={() => setMediaLoading(false)}
              fullscreen={fullscreen()}
              src={`${getHostStatic()}/${path}/${data().at((index() + 1) % data().length)}`}
            />
          </Show>
        </div>
        <footer class={clsx(
          showCounter() ? 'bg-neutral-800' : 'bg-transparent',
          'fixed bottom-8 left-1/2 -translate-x-1/2 w-40 h-40 rounded-lg flex flex-col items-center justify-center px-3 duration-150 opacity-90 text-center group'
        )}>
          <div class="flex justify-center">
            <div class={clsx(
              showCounter() ? 'block' : 'hidden',
              'font-semibold text-5xl text-blue-400'
            )}>
              {Number(index()) + 1} / {data().length}
            </div>
          </div>
        </footer>
      </Show>
    </div>
  )
}

export default Gallery
